### ISSUE TITLE
Could you provide the template for the boxes?you didn't choose the best games for many systems

### ISSUE THREAD

**Issue by zanzabarjones** [RetroHursty69/es-theme-greenilicious#1]
your stuff is almost perfect,I'm just bothered by many of the choices for the boxart,they're not choices people who owned the systems would have gone with,not even the top rated games for the systems in some cases cases,why would you choose golf games as representative for tg16 and gamecube when there were far better games? personally I agree with 90%  of your choices...also could you provide the templates so we could do a nekketsu collection for river city ransom...greenlicious and box alloy are great themes they're the themes I personally use and the themes I use when building systems for others ...could you provide alternate boxes/boxart for some systems using showcase games ie the top rated games for the systems

**Comment by RetroHursty69** [comment]
Sorry you have been bothered by my choices. There are plenty of cool themes out there to choose from if mine don't make the cut as they are.
